name: Scrape latest data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
      - run: ./scrape.sh
